# Meta Data for SEO

## Homepage
title = "Litestream"
titleSeparator = "-"
titleAddition = "Streaming SQLite Replication"
description = "Litestream replicates SQLite databases in real-time to S3."

## Open Graph + Twitter Cards
images = ["litestream.png"]
twitterSite = "litestreamio"
twitterCreator = "litestreamio"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "litestream.png"
schemaTwitter = "https://twitter.com/litestreamio"
schemaGitHub = "https://github.com/benbjohnson/litestream"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
# footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> + <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Litestream? <a class=\"alert-link\" href=\"https://github.com/benbjohnson/litestream/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/benbjohnson/litestreamio"
editPage = true
