name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build v0.5 (latest) documentation
        run: |
          git fetch origin main
          git checkout main
          npm run build
          mkdir -p /tmp/public-combined
          cp -r public/* /tmp/public-combined/

      - name: Build v0.3 (previous) documentation
        run: |
          git fetch origin docs-v0.3
          git checkout docs-v0.3
          npm run build -- --baseURL=https://litestream.io/v0.3/
          mkdir -p /tmp/public-combined/v0.3
          cp -r public/* /tmp/public-combined/v0.3/

      - name: Prepare combined build
        run: |
          rm -rf public
          cp -r /tmp/public-combined public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
